export const SEARCH_TOP_NEWS_REQUEST = 'SEARCH_TOP_NEWS_REQUEST';
export const SEARCH_TOP_NEWS_SUCCESS = 'SEARCH_TOP_NEWS_SUCCESS';
export const SEARCH_TOP_NEWS_ERROR = 'SEARCH_TOP_NEWS_ERROR';
export const SEARCH_ANY_NEWS_REQUEST = 'SEARCH_ANY_NEWS_REQUEST';
export const SEARCH_ANY_NEWS_SUCCESS = 'SEARCH_ANY_NEWS_SUCCESS';
export const SEARCH_ANY_NEWS_ERROR = 'SEARCH_ANY_NEWS_ERROR';
